services:
  db:
    image: ghcr.io/wy-studio/wy-postgres:16.4
    container_name: postgres.wooyeon
    ports: ["8281:5432"]
    environment:
      - POSTGRES_USER=wooyeon
      - POSTGRES_PASSWORD=wooyeon
      - POSTGRES_DB=wy-postgres
    volumes:
      - ${HOME}/wooyeon/wy-backend/data:/var/lib/postgresql/data
    networks: [wooyeon]

  app:
    image: ghcr.io/WY-Studio/wy-backend:lastest
    environment:
      - DATABASE_URL=postgresql://wooyeon:wooyeon@postgres.wooyeon:5432/wy-postgres
    depends_on: [db]
    ports: ["3000:3000"]
    networks: [wooyeon]

networks:
  wooyeon: {}