services:
  db:
    image: ghcr.io/wy-studio/wy-postgres:16.4
    container_name: postgres.wooyeon
    ports: ["8281:5432"]
    environment:
      - POSTGRES_USER=wooyeon
      - POSTGRES_PASSWORD=wooyeon
      - POSTGRES_DB=wy-postgres
    volumes:
      - /wooyeon/wy_backend/data:/var/lib/postgresql/data
    networks: [wooyeon]

  app:
    image: ghcr.io/wy-studio/wy-backend:latest
    container_name: backend.wooyeon
    env_file:
      - /wooyeon/wy_backend/.env
    depends_on: [db]
    ports: ["8280:3000"]
    networks: [wooyeon]
    restart: unless-stopped

networks:
  wooyeon: {}
