//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub use super::tb_user::Entity as TbUser;
pub use super::tb_user_photo::Entity as TbUserPhoto;
pub use super::tb_user_provider::Entity as TbUserProvider;
