//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(unique)]
    pub p_num: String,
    #[sea_orm(unique)]
    pub n_name: String,
    pub gender: i16,
    pub birth_date: Date,
    pub created_at: DateTimeWithTimeZone,
    pub status: i16,
    pub job: String,
    pub city: String,
    pub district: String,
    pub height_cm: i32,
    pub body_type: String,
    pub smoking: String,
    pub drinking: String,
    pub religion: String,
    pub mbti: Option<String>,
    pub preferred_age_group: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub personalities: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub hobbies: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub introduction: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub appeal_topics: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
