//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_user_photo")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub photo_id: Uuid,
    pub user_id: Uuid,
    pub photo_url: String,
    pub is_main: bool,
    pub is_approved: bool,
    pub uploaded_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
